### ISSUE TITLE
CORS problems

### ISSUE THREAD

**Issue by ageorgou** [oracc/oracc-rest#1]
When trying to combine with this with the Angular front-end, we have been getting failures due to browser implementations of the Same Origin Policy, based on CORS (Cross-Origin Resource Sharing). From looking into it a bit, this looks like it should be expected, as Angular and Flask are running on different ports and [are therefore considered different origins](https://stackoverflow.com/a/19966772).

What we need to do, in brief, is to add the appropriate metadata/headers to Flask's HTTP responses which will allow Angular to display the response data. The [Flask-CORS](http://flask-cors.readthedocs.io/en/latest/)  library should do this, in principle, but it doesn't seem to work for some reason. We have therefore switched to using pure Flask (`no-rest` branch) instead of Flask-restful, to try this in more detail. We have it working on @raquel-ucl's machine, but not the Azure VMs we were testing (not clear why it's not working there).

Some ideas of what could be going wrong / what we should do:
- It's possible that the Angular request is ["preflighted"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests), in which case we also need to handle the `OPTIONS` call that precedes the `GET`.
    - We should check the request sent by Angular (or received by Flask(-restful)) to see its headers; even something as simple as the `Content-Type` being non-standard would trigger the preflight process.
- We might need to set up Flask-CORS more carefully, not just with the default options.

**Comment by raquel-ucl** [comment]
Fixed by #3.
