### ISSUE TITLE
Support partial return of results

### ISSUE THREAD

**Issue by ageorgou** [oracc/oracc-rest#13]
We need to be able to retrieve results lazily, i.e. a "page" at a time, to avoid long loading times. See also oracc/oracc-search-front-end#11.

ElasticSearch offers several options for getting paged results:
- The [`from` and `size` fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html); this has a limit (by default 10000, which we may exceed) past which it becomes disallowed, or at least very inefficient.
- [Scrolling](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html); this is not meant to be used for real-time requests, but rather for processing large amounts of data on the back-end.
- The [`search_after` option](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html) seems like the best solution. It requires keeping track of the last result (glossary entry), but does not look too complex to implement. Performance is not clear, as it seems that the search is repeated each time, but that might also be true of the other options.

Regardless of the choice, we will also need to extend the search endpoints to accept a field on which to sort.

**Comment by ageorgou** [comment]
Note that with newer (5+) versions of ElasticSearch have changed how text fields are indexed. Sorting on the field itself is not supported, but it is possible to search on e.g. `cf.keyword`. This is an automatically created field, so no change to the mapping should be required. See [here](https://www.elastic.co/blog/strings-are-dead-long-live-strings) or [here](https://discuss.elastic.co/t/is-sorting-on-text-string-field-no-longer-available-in-5-x/68586/2), for example.

(It may be possible to do this with a single field by enabling `fielddata` during indexing, but that seems both more complex and not recommended, so not pursuing this for now)

**Comment by ageorgou** [comment]
Dealt with in #13, but #15 will improve this, so leaving open until that is merged.

**Comment by tim-band** [comment]
I don't think we can do this when we are sorting on the front end.
